export class Knjiga{
    autori:string;
    godina:string;
    id:number;
    zanrovi:string;
    slika:string;
    naziv:string;
    izdavac:string;
    jezik:string;
    status:string;
    zaduzena:number
    popularnost:number
    produzio:Boolean
    url;
    stanje:number
    ocena:number
    brojdana:Number
    username:string;
    datumu:Date
    datumv:Date
    ubacena:boolean
}